language: cpp
sudo: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

# We need newer compilers for c++11
# Lockdev is a linux dependency
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5.2" CC="gcc-5.2"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - liblockdev1-dev

before_script:
  - cd build
  - cmake ..

script:
  - $CXX --version
  - make
