language: cpp
sudo: false

compiler:
  - clang
  - gcc
os:
  - linux
  - osx

# We need newer compilers for c++11
install:
  # /usr/bin/gcc is v4.6 by default, but newer gcc package (gcc-X prefixed) is available.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" == "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi; fi;
  # /usr/bin/clang is v3.4 by default, and newer clang package (clang-X.Y prefixed) is available.
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then if  [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi; fi;

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - liblockdev1-dev

before_script:
  - cd build/
  - cmake ..

script:
  - make
