language: cpp
sudo: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

install:
if [[ ${TRAVIS_OS_NAME} = linux ]]; then
    # /usr/bin/gcc is v4.6 by default, but newer gcc package (gcc-X.Y prefixed) is available.
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    # /usr/bin/clang is v3.4 by default, and newer clang package (NOT prefixed) is available.
    #- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - echo ${PATH}
    - ls /usr/local
    - ls /usr/local/bin
    - export PATH=/usr/local/bin:/usr/bin:${PATH}
    - echo ${CXX}
    - ${CXX} --version
fi

# We need newer compilers for c++11
# Lockdev is a linux dependency
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - liblockdev1-dev

before_script:
  - cd build
  - cmake ..

script:
  - make
